import torch
import pickle

import causalities
import data_generators as dg


if __name__ == "__main__":
    encoder_dict = {
        "flow_temporal_encoder": {
            "attention_layers": 3,
            "attention_heads": 3,
            "attention_dim": 12,
            "attention_feedforward_dim": 8,
            "dropout": 0.1,
            "masked_time_series": None,
        },
    }

    model_parameters = {
        "flow_series_embedding_dim": 4,
        "flow_input_encoder_layers": 6,
        "bagging_size": None,
        "input_encoding_normalization": True,
        "data_normalization": "none",
        "loss_normalization": "both",
        "positional_encoding": {
            "dropout": 0.1,
        },
        **encoder_dict,
        "copula_decoder": {
            # flow_input_dim and copula_input_dim are passed by the TACTIS module dynamically
            "min_u": 0.05,
            "max_u": 0.95,
            "dsf_marginal": {
                "mlp_layers": 2,
                "mlp_dim": 3,
                "flow_layers": 3,
                "flow_hid_dim": 6,
            },
        },
    }

    if torch.cuda.is_available():
        device = torch.device("cuda")
    else:
        device = torch.device("cpu")

    # num_samples = 10000
    # data_generator = dg.Cut_V(4, 0.5, "cut_v")
    # data = []
    # for _ in range(num_samples):
    #     data.append(torch.transpose(data_generator.generate_data(20), 1, 0))
    # data = torch.stack(data).to(device)
    # causal_graph = data_generator.true_causal_graph()
    #
    # with open("cut_v.pkl", "wb") as f:
    #     pickle.dump((data, causal_graph), f)

    with open("cut_v.pkl", "rb") as f:
        input_tokens, causal_graph = pickle.load(f)
    input_tokens = input_tokens.to(device)

    print("true causality graph:", causal_graph)

    # true_causality_graph = torch.stack(causalities.generate_causalities(input_tokens[:1000], "retrain", model_parameters))
    # print("causality graph generated by the grand true method:")
    # print(true_causality_graph)

    causality_graph = torch.stack(causalities.generate_causalities(input_tokens[:1000], "constant series", model_parameters))
    print("causality graph generated by the constant series method:")
    print(causality_graph)
